Repository zama-ai/fhevm, pull requests merged in 2025-08, with the labels that each got.

#670 chore(sdk): make keys directory optional
  sdk/rust-sdk/examples/minimal-public-decryption-request.rs
  sdk/rust-sdk/examples/minimal-public-decryption-response.rs
  sdk/rust-sdk/examples/minimal-user-decryption-request.rs
  sdk/rust-sdk/examples/minimal-user-decryption-response.rs
  sdk/rust-sdk/src/lib.rs
Labels: cla-signed

#676 chore(gateway-contracts): remove contractsChainId from user/delegate structs
  gateway-contracts/contracts/Decryption.sol
  gateway-contracts/contracts/interfaces/IDecryption.sol
  gateway-contracts/rust_bindings/src/decryption.rs
  gateway-contracts/test/utils/eip712.ts
Labels: cla-signed

#649 feat(gateway-contracts): add getters to get txSenders involved in consensus
  gateway-contracts/contracts/CiphertextCommits.sol
  gateway-contracts/contracts/Decryption.sol
  gateway-contracts/contracts/InputVerification.sol
  gateway-contracts/contracts/MultichainAcl.sol
  gateway-contracts/contracts/interfaces/ICiphertextCommits.sol
  gateway-contracts/contracts/interfaces/IDecryption.sol
  gateway-contracts/contracts/interfaces/IInputVerification.sol
  gateway-contracts/contracts/interfaces/IMultichainAcl.sol
  gateway-contracts/rust_bindings/src/ciphertextcommits.rs
  gateway-contracts/rust_bindings/src/decryption.rs
  gateway-contracts/rust_bindings/src/iciphertextcommits.rs
  gateway-contracts/rust_bindings/src/idecryption.rs
  gateway-contracts/rust_bindings/src/iinputverification.rs
  gateway-contracts/rust_bindings/src/imultichainacl.rs
  gateway-contracts/rust_bindings/src/inputverification.rs
  gateway-contracts/rust_bindings/src/multichainacl.rs
  gateway-contracts/selectors.txt
  gateway-contracts/test/CiphertextCommits.ts
  gateway-contracts/test/Decryption.ts
  gateway-contracts/test/InputVerification.ts
  gateway-contracts/test/MultichainAcl.ts
Labels: cla-signed

#460 GPU Memory tracking / management
  coprocessor/fhevm-engine/Cargo.lock
  coprocessor/fhevm-engine/coprocessor/src/tests/utils.rs
  coprocessor/fhevm-engine/fhevm-engine-common/Cargo.toml
  coprocessor/fhevm-engine/fhevm-engine-common/src/gpu_memory.rs
  coprocessor/fhevm-engine/fhevm-engine-common/src/lib.rs
  coprocessor/fhevm-engine/fhevm-engine-common/src/tfhe_ops.rs
  coprocessor/fhevm-engine/fhevm-engine-common/src/types.rs
  coprocessor/fhevm-engine/scheduler/src/dfg/scheduler.rs
  coprocessor/fhevm-engine/sns-executor/src/executor.rs
Labels: cla-signed

#681 chore(gateway-contracts): clean unused objects
  gateway-contracts/contracts/CiphertextCommits.sol
  gateway-contracts/contracts/interfaces/ICiphertextCommits.sol
  gateway-contracts/rust_bindings/src/ciphertextcommits.rs
  gateway-contracts/rust_bindings/src/iciphertextcommits.rs
  gateway-contracts/selectors.txt
Labels: cla-signed

#683 chore(kms-connector): rustle integration for wss connection
  kms-connector/Cargo.lock
  kms-connector/Cargo.toml
  kms-connector/simple-connector/Cargo.toml
  kms-connector/simple-connector/src/bin/kms-connector.rs
Labels: docker, cla-signed

#673 fix(sdk): ci filters fix
  .github/workflows/sdk-rust-sdk-tests.yml
  sdk/rust-sdk/scripts/run-examples.sh
Labels: cla-signed

#687 chore(kms-connector): pin bindings version
  kms-connector/Cargo.lock
  kms-connector/Cargo.toml
Labels: cla-signed

#686 feat(kms-connector): configurable polling for listener
  kms-connector/config/gw-listener.toml
  kms-connector/config/kms-worker.toml
  kms-connector/config/tx-sender.toml
  kms-connector/crates/gw-listener/src/core/config/parsed.rs
  kms-connector/crates/gw-listener/src/core/config/raw.rs
  kms-connector/crates/gw-listener/src/core/gw_listener.rs
  test-suite/fhevm/env/staging/.env.connector
  test-suite/fhevm/fhevm-cli
Labels: cla-signed

#654 feat(test-suite): add http public decrypt benchmark task
  test-suite/benchmarks/contracts/PublicDecryptBenchmark.sol
  test-suite/benchmarks/hardhat.config.ts
  test-suite/benchmarks/tasks/publicDecryptBenchmark.ts
Labels: cla-signed

#660 fix(coprocessor): fhevm-listener, check chain_id consistency of blockchain vs tenant
  coprocessor/fhevm-engine/host-listener/.sqlx/query-d090bb03d3a480f8c37b45498c5cc85742b3509cef16429687f65cc2335b422f.json
  coprocessor/fhevm-engine/host-listener/src/cmd/mod.rs
  coprocessor/fhevm-engine/host-listener/src/database/tfhe_event_propagate.rs
  coprocessor/fhevm-engine/host-listener/tests/integration_test.rs
  coprocessor/fhevm-engine/test-harness/src/instance.rs
  coprocessor/fhevm-engine/tfhe-worker/src/tests/operators_from_events.rs
Labels: cla-signed

#691 fix(coprocessor): host-listener, handle reorgs
  coprocessor/fhevm-engine/Cargo.lock
  coprocessor/fhevm-engine/Cargo.toml
  coprocessor/fhevm-engine/host-listener/src/cmd/block_history.rs
  coprocessor/fhevm-engine/host-listener/src/cmd/mod.rs
  coprocessor/fhevm-engine/host-listener/tests/integration_test.rs
Labels: cla-signed

#698 fix(coprocessor): do not expand an empty compact ct list
  coprocessor/fhevm-engine/Cargo.lock
  coprocessor/fhevm-engine/transaction-sender/src/ops/verify_proof.rs
  coprocessor/fhevm-engine/transaction-sender/tests/verify_proof_tests.rs
  coprocessor/fhevm-engine/zkproof-worker/Cargo.toml
  coprocessor/fhevm-engine/zkproof-worker/src/tests/mod.rs
  coprocessor/fhevm-engine/zkproof-worker/src/tests/utils.rs
  coprocessor/fhevm-engine/zkproof-worker/src/verifier.rs
Labels: cla-signed

#704 chore(kms-connector): add version endpoint
  kms-connector/Cargo.lock
  kms-connector/Cargo.toml
  kms-connector/crates/gw-listener/Dockerfile
  kms-connector/crates/gw-listener/src/monitoring/health.rs
  kms-connector/crates/gw-listener/tests/health.rs
  kms-connector/crates/kms-worker/Dockerfile
  kms-connector/crates/kms-worker/src/monitoring/health.rs
  kms-connector/crates/kms-worker/tests/health.rs
  kms-connector/crates/tx-sender/Dockerfile
  kms-connector/crates/tx-sender/src/monitoring/health.rs
  kms-connector/crates/tx-sender/tests/health.rs
  kms-connector/crates/utils/Cargo.toml
  kms-connector/crates/utils/src/monitoring/health.rs
  kms-connector/crates/utils/src/monitoring/server.rs
Labels: cla-signed

#710 feat(kms-connector): add db polling backup
  kms-connector/crates/kms-worker/src/core/config/parsed.rs
  kms-connector/crates/kms-worker/src/core/config/raw.rs
  kms-connector/crates/kms-worker/src/core/event_picker.rs
  kms-connector/crates/kms-worker/src/core/kms_worker.rs
  kms-connector/crates/kms-worker/tests/event_picker/parallel.rs
  kms-connector/crates/kms-worker/tests/event_picker/simple.rs
  kms-connector/crates/tx-sender/src/core/config/parsed.rs
  kms-connector/crates/tx-sender/src/core/config/raw.rs
  kms-connector/crates/tx-sender/src/core/kms_response_picker.rs
  kms-connector/crates/tx-sender/src/core/tx_sender.rs
  kms-connector/crates/tx-sender/tests/integration_tests.rs
  kms-connector/crates/tx-sender/tests/response_picker.rs
Labels: cla-signed

#713 fix(coprocessor): semantic for bitwise ops with binary and scalar
  coprocessor/fhevm-engine/fhevm-engine-common/src/tfhe_ops.rs
Labels: cla-signed

#716 feat(coprocessor): add metrics in txn-sender
  coprocessor/fhevm-engine/Cargo.lock
  coprocessor/fhevm-engine/transaction-sender/Cargo.toml
  coprocessor/fhevm-engine/transaction-sender/src/bin/transaction_sender.rs
  coprocessor/fhevm-engine/transaction-sender/src/config.rs
  coprocessor/fhevm-engine/transaction-sender/src/http_server.rs
  coprocessor/fhevm-engine/transaction-sender/src/lib.rs
  coprocessor/fhevm-engine/transaction-sender/src/metrics.rs
  coprocessor/fhevm-engine/transaction-sender/src/ops/add_ciphertext.rs
  coprocessor/fhevm-engine/transaction-sender/src/ops/allow_handle.rs
  coprocessor/fhevm-engine/transaction-sender/src/ops/verify_proof.rs
  test-suite/fhevm/config/prometheus/prometheus.yml
Labels: cla-signed

#677 chore(library-solidity): reflect changes for new decryptionProof containing signatures and extraData
  .github/workflows/common-pull-request-lint.yml
  .github/workflows/library-solidity-hardhat-tests.yml
  library-solidity/CustomProvider.ts
  library-solidity/examples/FHEVMConfig.sol
  library-solidity/examples/TestAsyncDecrypt.sol
  library-solidity/fhevmTemp/addresses/ACLAddress.sol
  library-solidity/fhevmTemp/addresses/FHEVMExecutorAddress.sol
  library-solidity/fhevmTemp/addresses/FHEVMHostAddresses.sol
  library-solidity/fhevmTemp/addresses/InputVerifierAddress.sol
  library-solidity/fhevmTemp/addresses/KMSVerifierAddress.sol
  library-solidity/hardhat.config.ts
  library-solidity/lib/FHE.sol
  library-solidity/tasks/taskDeploy.ts
  library-solidity/test/asyncDecrypt.ts
  library-solidity/test/coprocessorUtils.ts
  library-solidity/test/fhevmjsMocked.ts
  library-solidity/test/gatewayDecrypt/testAsyncDecrypt.ts
  library-solidity/test/instance.ts
Labels: cla-signed

#717 chore(test-suite): improve user/public decryption benchmarks
  test-suite/benchmarks/.env.example
  test-suite/benchmarks/.gitignore
  test-suite/benchmarks/Makefile
  test-suite/benchmarks/README.md
  test-suite/benchmarks/contracts/PublicDecryptBenchmark.sol
  test-suite/benchmarks/contracts/UserDecryptBenchmark.sol
  test-suite/benchmarks/tasks/publicDecryptBenchmark.ts
  test-suite/benchmarks/tasks/shared.ts
  test-suite/benchmarks/tasks/userDecryptBenchmark.ts
Labels: cla-signed

#726 chore(coprocessor): structured log in zkproof/tfhe-worker
  coprocessor/fhevm-engine/tfhe-worker/src/lib.rs
  coprocessor/fhevm-engine/tfhe-worker/src/metrics.rs
  coprocessor/fhevm-engine/zkproof-worker/src/bin/zkproof_worker.rs
  coprocessor/fhevm-engine/zkproof-worker/src/verifier.rs
Labels: cla-signed

#721 fix(coprocessor): tfhe-worker, health check
  coprocessor/fhevm-engine/Cargo.lock
  coprocessor/fhevm-engine/fhevm-engine-common/src/utils.rs
  coprocessor/fhevm-engine/host-listener/src/cmd/mod.rs
  coprocessor/fhevm-engine/host-listener/src/database/tfhe_event_propagate.rs
  coprocessor/fhevm-engine/host-listener/src/health_check.rs
  coprocessor/fhevm-engine/scheduler/src/dfg/scheduler.rs
  coprocessor/fhevm-engine/tfhe-worker/Cargo.toml
  coprocessor/fhevm-engine/tfhe-worker/benches/utils.rs
  coprocessor/fhevm-engine/tfhe-worker/src/daemon_cli.rs
  coprocessor/fhevm-engine/tfhe-worker/src/health_check.rs
  coprocessor/fhevm-engine/tfhe-worker/src/lib.rs
  coprocessor/fhevm-engine/tfhe-worker/src/tests/health_check.rs
  coprocessor/fhevm-engine/tfhe-worker/src/tests/mod.rs
  coprocessor/fhevm-engine/tfhe-worker/src/tests/utils.rs
  coprocessor/fhevm-engine/tfhe-worker/src/tfhe_worker.rs
Labels: cla-signed

#730 Enable fhe operand check in tfhe-worker (TOB-ZCOPRO-21‬)
  coprocessor/fhevm-engine/tfhe-worker/src/tfhe_worker.rs
Labels: cla-signed

#738 chore(gateway-contracts): upgrade alloy for bindings
  .github/workflows/gateway-contracts-integrity-checks.yml
  gateway-contracts/rust_bindings/Cargo.toml
  gateway-contracts/rust_bindings/src/ciphertext_commits.rs
  gateway-contracts/rust_bindings/src/context_upgradeable.rs
  gateway-contracts/rust_bindings/src/decryption.rs
  gateway-contracts/rust_bindings/src/ecdsa.rs
  gateway-contracts/rust_bindings/src/eip712_upgradeable.rs
  gateway-contracts/rust_bindings/src/empty_uups_proxy.rs
  gateway-contracts/rust_bindings/src/erc1967_utils.rs
  gateway-contracts/rust_bindings/src/errors.rs
  gateway-contracts/rust_bindings/src/extra_data.rs
  gateway-contracts/rust_bindings/src/fhe_type_bit_sizes.rs
  gateway-contracts/rust_bindings/src/gateway_config.rs
  gateway-contracts/rust_bindings/src/gateway_config_checks.rs
  gateway-contracts/rust_bindings/src/handle_ops.rs
  gateway-contracts/rust_bindings/src/handleops.rs
  gateway-contracts/rust_bindings/src/i_beacon.rs
  gateway-contracts/rust_bindings/src/i_ciphertext_commits.rs
  gateway-contracts/rust_bindings/src/i_decryption.rs
  gateway-contracts/rust_bindings/src/i_gateway_config.rs
  gateway-contracts/rust_bindings/src/i_input_verification.rs
  gateway-contracts/rust_bindings/src/i_kms_management.rs
  gateway-contracts/rust_bindings/src/i_multichain_acl.rs
  gateway-contracts/rust_bindings/src/ierc1822_proxiable.rs
  gateway-contracts/rust_bindings/src/ierc1967.rs
  gateway-contracts/rust_bindings/src/ierc5267.rs
  gateway-contracts/rust_bindings/src/initializable.rs
  gateway-contracts/rust_bindings/src/input_verification.rs
  gateway-contracts/rust_bindings/src/kms_management.rs
  gateway-contracts/rust_bindings/src/math.rs
  gateway-contracts/rust_bindings/src/message_hash_utils.rs
  gateway-contracts/rust_bindings/src/mod.rs
  gateway-contracts/rust_bindings/src/multichain_acl.rs
  gateway-contracts/rust_bindings/src/ownable2_step_upgradeable.rs
  gateway-contracts/rust_bindings/src/ownable_upgradeable.rs
  gateway-contracts/rust_bindings/src/ownableupgradeable.rs
  gateway-contracts/rust_bindings/src/panic.rs
  gateway-contracts/rust_bindings/src/pausable_upgradeable.rs
  gateway-contracts/rust_bindings/src/safe_cast.rs
  gateway-contracts/rust_bindings/src/signed_math.rs
  gateway-contracts/rust_bindings/src/storage_slot.rs
  gateway-contracts/rust_bindings/src/strings.rs
  gateway-contracts/rust_bindings/src/uups_upgradeable.rs
  gateway-contracts/rust_bindings/src/uups_upgradeable_empty_proxy.rs
  gateway-contracts/scripts/bindings_update.py
Labels: cla-signed

#749 fix(test-suite): use anvil 1.2.3
  test-suite/fhevm/docker-compose/gateway-docker-compose.yml
  test-suite/fhevm/docker-compose/host-docker-compose.yml
Labels: cla-signed

#753 chore(sdk): gateway bindings in sdk
  sdk/rust-sdk/Cargo.lock
  sdk/rust-sdk/Cargo.toml
  sdk/rust-sdk/artifacts/contract-abis/Decryption.json
  sdk/rust-sdk/artifacts/contract-abis/DecryptionOracle.json
  sdk/rust-sdk/artifacts/contract-abis/InputVerification.json
  sdk/rust-sdk/examples/minimal-user-decryption-request.rs
  sdk/rust-sdk/examples/minimal-user-decryption-response.rs
  sdk/rust-sdk/src/blockchain/bindings.rs
  sdk/rust-sdk/src/blockchain/calldata.rs
  sdk/rust-sdk/src/blockchain/mod.rs
  sdk/rust-sdk/src/decryption/user/deserializer.rs
  sdk/rust-sdk/src/decryption/user/request.rs
  sdk/rust-sdk/src/decryption/user/response.rs
  sdk/rust-sdk/src/decryption/user/types.rs
  sdk/rust-sdk/test_data/user_decryption_test_data.json
Labels: cla-signed

#754 chore(test-suite): update fhevm to 0.8.0-2 and fhevm-relayer to 0.3.0
  test-suite/fhevm/fhevm-cli
Labels: cla-signed

#751 fix(coprocessor): host-listener, recheck_block, never skipped, error handling, log
  coprocessor/fhevm-engine/host-listener/src/cmd/mod.rs
Labels: cla-signed

#595 docs(common): correct couple of typos
  docs/examples/fhe-decrypt-multiple-values-in-solidity.md
Labels: documentation, cla-signed

#747 docs(common): remove the EOL banner
  docs/protocol/README.md
Labels: documentation, cla-signed

#661 docs(common): add OZ reference to main doc
  docs/examples/SUMMARY.md
  docs/protocol/SUMMARY.md
Labels: documentation, cla-signed

#757 chore(test-suite): bump to fhevm 0.8.3 and fhevm-relayer 0.3.1
  test-suite/fhevm/fhevm-cli
Labels: cla-signed

#759 fix(sdk): add extra_data for eip712
  sdk/rust-sdk/src/signature/eip712/builder.rs
  sdk/rust-sdk/src/signature/eip712/types.rs
Labels: cla-signed

#761 docs(common): mirror doc link updates in the x0.7
  coprocessor/docs/README.md
  docs/protocol/README.md
  docs/sdk-guides/sdk-overview.md
  docs/solidity-guides/README.md
  gateway-contracts/docs/README.md
Labels: documentation, cla-signed

#740 chore(common): add zizmor check in ci
  .github/actions/gpu_setup/action.yml
  .github/workflows/charts-helm-checks.yml
  .github/workflows/common-pull-request-lint.yml
  .github/workflows/coprocessor-benchmark-cpu.yml
  .github/workflows/coprocessor-benchmark-gpu.yml
  .github/workflows/coprocessor-cargo-clippy.yml
  .github/workflows/coprocessor-cargo-fmt.yml
  .github/workflows/coprocessor-cargo-listener-tests.yml
  .github/workflows/coprocessor-cargo-tests.yml
  .github/workflows/coprocessor-db-migration-docker-build.yml
  .github/workflows/coprocessor-gpu-tests.yml
  .github/workflows/coprocessor-gw-listener-docker-build.yml
  .github/workflows/coprocessor-host-listener-docker-build.yml
  .github/workflows/coprocessor-sns-worker-docker-build.yml
  .github/workflows/coprocessor-tfhe-worker-docker-build.yml
  .github/workflows/coprocessor-tx-sender-docker-build.yml
  .github/workflows/coprocessor-zkproof-worker-docker-build.yml
  .github/workflows/gateway-contracts-docker-build.yml
  .github/workflows/gateway-contracts-hardhat-tests-docker.yml
  .github/workflows/gateway-contracts-hardhat-tests.yml
  .github/workflows/gateway-contracts-mock-deployment.yml
  .github/workflows/golden-container-images-docker-build-nodejs.yml
  .github/workflows/golden-container-images-docker-build-rust.yml
  .github/workflows/host-contracts-docker-build.yml
  .github/workflows/host-contracts-hardhat-forge-tests.yml
  .github/workflows/host-contracts-publish.yml
  .github/workflows/host-contracts-slither-analysis.yml
  .github/workflows/kms-connector-db-migration-docker-build.yml
  .github/workflows/kms-connector-gw-listener-docker-build.yml
  .github/workflows/kms-connector-kms-worker-docker-build.yml
  .github/workflows/kms-connector-tx-sender-docker-build.yml
  .github/workflows/library-solidity-hardhat-tests.yml
  .github/workflows/library-solidity-publish.yml
  .github/workflows/sdk-rust-sdk-tests.yml
  .github/workflows/test-suite-docker-build.yml
  .github/workflows/test-suite-e2e-operators-tests.yml
  .github/workflows/test-suite-e2e-tests-with-build.yml
  .github/workflows/test-suite-e2e-tests.yml
Labels: cla-signed

#765 chore(sdk): remove openssl from deps
  sdk/rust-sdk/Cargo.lock
  sdk/rust-sdk/Cargo.toml
Labels: cla-signed

#769 feat(charts): add custom command for kms-connector db migration
  charts/kms-connector/Chart.yaml
  charts/kms-connector/templates/kms-connector-db-migration.yaml
  charts/kms-connector/values.yaml
Labels: cla-signed

#744 fix(coprocessor): host-listener, more reliable block time estimation
  coprocessor/fhevm-engine/host-listener/src/cmd/block_history.rs
  coprocessor/fhevm-engine/host-listener/src/cmd/mod.rs
Labels: cla-signed

#775 docs(common): update HCU values in docs
  docs/solidity-guides/hcu.md
Labels: cla-signed

#752 fix(coprocessor): host-listener, recheck on prev block broken by reorg handling
  coprocessor/fhevm-engine/host-listener/src/cmd/mod.rs
Labels: cla-signed

#777 feat(charts): fix contracts upgrade configmap version patch
  charts/contracts/Chart.yaml
  charts/contracts/templates/sc-deploy-config.yaml
Labels: cla-signed

#782 chore(gateway-contracts): rename bindings
  gateway-contracts/rust_bindings/Cargo.toml
  gateway-contracts/rust_bindings/abi/TFHETypeBitSizes.abi
  kms-connector/Cargo.lock
  kms-connector/Cargo.toml
  kms-connector/crates/gw-listener/Cargo.toml
  kms-connector/crates/gw-listener/src/core/event_publisher.rs
  kms-connector/crates/gw-listener/src/core/gw_listener.rs
  kms-connector/crates/gw-listener/tests/integration_test.rs
  kms-connector/crates/kms-worker/Cargo.toml
  kms-connector/crates/kms-worker/src/core/event_processor/decryption.rs
  kms-connector/crates/kms-worker/src/core/event_processor/s3.rs
  kms-connector/crates/kms-worker/tests/event_picker/parallel.rs
  kms-connector/crates/kms-worker/tests/event_picker/simple.rs
  kms-connector/crates/tx-sender/Cargo.toml
  kms-connector/crates/tx-sender/src/core/tx_sender.rs
  kms-connector/crates/tx-sender/tests/integration_tests.rs
  kms-connector/crates/utils/Cargo.toml
  kms-connector/crates/utils/src/tests/rand.rs
  kms-connector/crates/utils/src/tests/setup/deps.rs
  kms-connector/crates/utils/src/tests/setup/gw.rs
  kms-connector/crates/utils/src/tests/setup/instance.rs
  kms-connector/crates/utils/src/types/db.rs
  kms-connector/crates/utils/src/types/gw_event.rs
  sdk/rust-sdk/Cargo.lock
  sdk/rust-sdk/Cargo.toml
  sdk/rust-sdk/examples/minimal-user-decryption-request.rs
  sdk/rust-sdk/examples/minimal-user-decryption-response.rs
  sdk/rust-sdk/src/blockchain/calldata.rs
  sdk/rust-sdk/src/decryption/user/request.rs
  sdk/rust-sdk/src/decryption/user/response.rs
  sdk/rust-sdk/src/decryption/user/types.rs
Labels: cla-signed

#781 chore(kms-connector): remove verify_coprocessor config
  charts/kms-connector/Chart.yaml
  charts/kms-connector/values.yaml
  kms-connector/config/kms-worker.toml
  kms-connector/crates/kms-worker/src/core/config/parsed.rs
  kms-connector/crates/kms-worker/src/core/config/raw.rs
Labels: cla-signed

#722 docs(common): changed definitions to public decrypt and user decrypt
  docs/examples/SUMMARY.md
  docs/examples/fhe-public-decrypt-multiple-values.md
  docs/examples/fhe-public-decrypt-single-value.md
  docs/examples/fhe-user-decrypt-multiple-values.md
  docs/examples/fhe-user-decrypt-single-value.md
Labels: documentation, cla-signed

#785 feat(host-contracts): use new API for etherscan verification
  host-contracts/hardhat.config.ts
Labels: cla-signed

#788 chore(common): allow multiple e2e tests in parallel if triggered manually
  .github/workflows/test-suite-e2e-operators-tests.yml
  .github/workflows/test-suite-e2e-tests-with-build.yml
  .github/workflows/test-suite-e2e-tests.yml
Labels: cla-signed
